import { useEffect, useState } from 'react';
import { Alert, Button, Card, Form, Input, InputNumber, Modal, Select, Space, Table, Tag, Typography, message } from 'antd';
import { MinusCircleOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons';
import { ApiError, approveInventoryCount, createInventoryCount, listInventoryCounts, listLocations, listSkus, listWarehouses, saveInventoryCount, submitInventoryCount, transitionInventoryCount } from '../api/wms';
import type { InventoryCountView, MasterDataOption } from '../types';

export function CountPage() {
  const [items,setItems]=useState<InventoryCountView[]>([]),[warehouses,setWarehouses]=useState<MasterDataOption[]>([]),[skus,setSkus]=useState<MasterDataOption[]>([]),[locations,setLocations]=useState<MasterDataOption[]>([]);
  const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[editing,setEditing]=useState<InventoryCountView>(),[conflict,setConflict]=useState('');
  const [confirmationToken,setConfirmationToken]=useState<string>(),[approvalLines,setApprovalLines]=useState<Array<{sku:MasterDataOption;location:MasterDataOption;approvalBookTotal:number;difference:number}>>([]);
  const [page,setPage]=useState(0),[total,setTotal]=useState(0),[filters,setFilters]=useState<{countNo?:string;warehouseId?:number;status?:string}>({});
  const [form]=Form.useForm(),[editForm]=Form.useForm(),[filterForm]=Form.useForm();
  const refresh=async(nextPage=page,nextFilters=filters)=>{const result=await listInventoryCounts({...nextFilters,page:nextPage,size:20});setItems(result.items);setTotal(result.total);};
  useEffect(()=>{void refresh();void Promise.all([listWarehouses(),listSkus()]).then(([w,s])=>{setWarehouses(w);setSkus(s);});},[]);
  const warehouseChanged=async(id:number)=>{setLocations(await listLocations(id));form.setFieldValue('lines',[{}]);};
  const create=async()=>{try{const v=await form.validateFields();setBusy(true);await createInventoryCount(v.warehouseId,v.lines);message.success('盘点草稿已创建');setOpen(false);form.resetFields();await refresh();}finally{setBusy(false);}};
  const openEdit=(count:InventoryCountView)=>{setEditing(count);setConflict('');setConfirmationToken(undefined);setApprovalLines([]);void listLocations(count.warehouse.id).then(setLocations);editForm.setFieldsValue({note:count.note,lines:count.lines.map(v=>({skuId:v.sku.id,locationId:v.location.id,countedTotal:v.countedTotal,differenceReason:v.differenceReason}))});};
  const showError=(error:unknown)=>{if(error instanceof ApiError){const data=error.data as {current?:InventoryCountView;confirmationToken?:string;approvalLines?:Array<{sku:MasterDataOption;location:MasterDataOption;approvalBookTotal:number;difference:number}>};setConflict(`${error.code}：${error.message}${data?.current?`（服务端当前版本 ${data.current.version}）`:''}`);setConfirmationToken(data?.confirmationToken);setApprovalLines(data?.approvalLines??[]);return;}throw error;};
  const save=async()=>{if(!editing)return;try{setBusy(true);const values=await editForm.validateFields();const next=await saveInventoryCount(editing,values,`save-${crypto.randomUUID()}`);setEditing(next);setConflict('');message.success('草稿已保存');await refresh();}catch(e){showError(e);}finally{setBusy(false);}};
  const submit=async()=>{if(!editing)return;try{setBusy(true);const next=await submitInventoryCount(editing,`submit-${crypto.randomUUID()}`);setEditing(next);setConflict('');message.success('盘点已提交');await refresh();}catch(e){showError(e);}finally{setBusy(false);}};
  const runTransition=async(action:'REJECT'|'REOPEN'|'CANCEL')=>{if(!editing)return;let reason:string|undefined;if(action!=='REOPEN'){reason=window.prompt(action==='REJECT'?'请输入驳回原因':'请输入取消原因')??undefined;if(!reason?.trim())return;}try{setBusy(true);const next=await transitionInventoryCount(editing,action,reason);setEditing(next);setConflict('');message.success('状态已更新');await refresh();}catch(e){showError(e);}finally{setBusy(false);}};
  const copyCorrection=async()=>{if(!editing)return;try{setBusy(true);const next=await createInventoryCount(editing.warehouse.id,editing.lines.map(v=>({skuId:v.sku.id,locationId:v.location.id})),editing.id);setEditing(next);message.success('纠错盘点草稿已创建');await refresh();}catch(e){showError(e);}finally{setBusy(false);}};
  const approve=async(token?:string)=>{if(!editing)return;try{setBusy(true);const next=await approveInventoryCount(editing,token);setEditing(next);setConflict('');setConfirmationToken(undefined);setApprovalLines([]);message.success('盘点已批准，库存已校准');await refresh();}catch(e){showError(e);}finally{setBusy(false);}};
  const statusText=(status:InventoryCountView['status'])=>({DRAFT:'草稿',SUBMITTED:'待审核',REJECTED:'已驳回',APPROVED:'已批准',CANCELLED:'已取消'}[status]);
  return <Space direction="vertical" size="large" style={{width:'100%'}}>
    <Card><Space style={{display:'flex',justifyContent:'space-between'}}><div><Typography.Title level={3}>库存盘点</Typography.Title><Typography.Text type="secondary">录入物理实盘总量；空值表示尚未盘点，0 表示明确盘点为零。</Typography.Text></div><Space><Button icon={<ReloadOutlined/>} onClick={()=>void refresh()}>刷新</Button><Button type="primary" icon={<PlusOutlined/>} onClick={()=>setOpen(true)}>新建盘点</Button></Space></Space></Card>
    <Card><Form form={filterForm} layout="inline" onFinish={values=>{setFilters(values);setPage(0);void refresh(0,values);}} style={{marginBottom:16}}><Form.Item name="countNo"><Input placeholder="盘点单号" allowClear/></Form.Item><Form.Item name="warehouseId"><Select placeholder="仓库" allowClear style={{width:180}} options={warehouses.map(v=>({value:v.id,label:`${v.code} ${v.name}`}))}/></Form.Item><Form.Item name="status"><Select placeholder="状态" allowClear style={{width:140}} options={['DRAFT','SUBMITTED','REJECTED','APPROVED','CANCELLED'].map(v=>({value:v,label:statusText(v as InventoryCountView['status'])}))}/></Form.Item><Button htmlType="submit" type="primary">筛选</Button></Form><Table rowKey="id" dataSource={items} pagination={{current:page+1,pageSize:20,total,onChange:p=>{setPage(p-1);void refresh(p-1);}}} columns={[{title:'盘点单号',dataIndex:'countNo'},{title:'仓库',render:(_,r)=>`${r.warehouse.code} ${r.warehouse.name}`},{title:'状态',render:(_,r)=><Tag color={r.status==='DRAFT'?'blue':r.status==='SUBMITTED'?'gold':'default'}>{statusText(r.status)}</Tag>},{title:'维度数',render:(_,r)=>r.lines.length},{title:'操作',render:(_,r)=><Button type="link" onClick={()=>openEdit(r)}>{r.status==='DRAFT'?'录入':'查看'}</Button>}]}/></Card>
    <Modal title="新建盘点草稿" open={open} confirmLoading={busy} onCancel={()=>setOpen(false)} onOk={()=>void create()} width={720}><Form form={form} layout="vertical" initialValues={{lines:[{}]}}><Form.Item name="warehouseId" label="仓库" rules={[{required:true}]}><Select options={warehouses.map(v=>({value:v.id,label:`${v.code} ${v.name}`}))} onChange={warehouseChanged}/></Form.Item><Form.List name="lines">{(fields,{add,remove})=><>{fields.map(f=><Space key={f.key} align="baseline"><Form.Item {...f} name={[f.name,'skuId']} label="SKU" rules={[{required:true}]}><Select style={{width:230}} options={skus.map(v=>({value:v.id,label:`${v.code} ${v.name}`}))}/></Form.Item><Form.Item {...f} name={[f.name,'locationId']} label="库位" rules={[{required:true}]}><Select style={{width:200}} options={locations.map(v=>({value:v.id,label:v.code}))}/></Form.Item>{fields.length>1&&<MinusCircleOutlined onClick={()=>remove(f.name)}/>}</Space>)}<Button block type="dashed" icon={<PlusOutlined/>} onClick={()=>add()}>增加盘点维度</Button></>}</Form.List></Form></Modal>
    <Modal title={editing?`${editing.countNo} · ${statusText(editing.status)} · 版本 ${editing.version}`:'盘点详情'} open={!!editing} onCancel={()=>setEditing(undefined)} width={780} footer={editing?.status==='DRAFT'?[<Button key="cancel" danger loading={busy} onClick={()=>void runTransition('CANCEL')}>取消盘点</Button>,<Button key="save" loading={busy} onClick={()=>void save()}>保存草稿</Button>,<Button key="submit" type="primary" loading={busy} onClick={()=>void submit()}>提交盘点</Button>]:editing?.status==='SUBMITTED'?[<Button key="cancel" danger loading={busy} onClick={()=>void runTransition('CANCEL')}>取消盘点</Button>,<Button key="reject" loading={busy} onClick={()=>void runTransition('REJECT')}>驳回</Button>,<Button key="approve" type="primary" loading={busy} onClick={()=>void approve()}>批准并校准库存</Button>]:editing?.status==='REJECTED'?[<Button key="reopen" type="primary" loading={busy} onClick={()=>void runTransition('REOPEN')}>重新编辑</Button>]:editing?.status==='APPROVED'?[<Button key="correct" type="primary" loading={busy} onClick={()=>void copyCorrection()}>复制为纠错盘点</Button>]:<Button key="close" onClick={()=>setEditing(undefined)}>关闭</Button>}>
      {conflict&&<Alert showIcon type="error" message={conflict} style={{marginBottom:16}}/>}
      {confirmationToken&&<Card size="small" title="请确认最新盘点差异" style={{marginBottom:16}}><Table rowKey={r=>`${r.sku.id}-${r.location.id}`} pagination={false} dataSource={approvalLines} columns={[{title:'SKU',render:(_,r)=>`${r.sku.code} ${r.sku.name}`},{title:'库位',render:(_,r)=>`${r.location.code} ${r.location.name}`},{title:'最新账面',dataIndex:'approvalBookTotal'},{title:'最新差异',dataIndex:'difference'}]}/><Button type="primary" loading={busy} style={{marginTop:12}} onClick={()=>void approve(confirmationToken)}>确认最新差异并批准</Button></Card>}
      {editing?.rejectionReason&&<Alert type="warning" message={`驳回原因：${editing.rejectionReason}`} style={{marginBottom:16}}/>}{editing?.cancellationReason&&<Alert message={`取消原因：${editing.cancellationReason}`} style={{marginBottom:16}}/>}
      {editing?.approvedBy&&<Alert type="success" message={`审核人：${editing.approvedBy}；审核时间：${editing.approvedAt}`} style={{marginBottom:16}}/>}
      <Form form={editForm} layout="vertical" disabled={editing?.status!=='DRAFT'}><Form.Item name="note" label="备注"><Input.TextArea maxLength={500}/></Form.Item><Form.List name="lines">{(fields,{add,remove})=><>{fields.map(f=><Card size="small" key={f.key} style={{marginBottom:10}}><Space align="baseline"><Form.Item {...f} name={[f.name,'skuId']} label="SKU" rules={[{required:true}]}><Select style={{width:180}} options={skus.map(v=>({value:v.id,label:v.code}))}/></Form.Item><Form.Item {...f} name={[f.name,'locationId']} label="库位" rules={[{required:true}]}><Select style={{width:170}} options={locations.map(v=>({value:v.id,label:v.code}))}/></Form.Item><Form.Item {...f} name={[f.name,'countedTotal']} label="实盘总量"><InputNumber min={0} precision={0}/></Form.Item><Form.Item {...f} name={[f.name,'differenceReason']} label="差异说明"><Input style={{width:180}}/></Form.Item>{fields.length>1&&<MinusCircleOutlined onClick={()=>remove(f.name)}/>}</Space></Card>)}{editing?.status==='DRAFT'&&<Button block type="dashed" icon={<PlusOutlined/>} onClick={()=>add()}>增加盘点维度</Button>}</>}</Form.List></Form>
      {editing?.status==='APPROVED'&&<Table rowKey={row=>`${row.sku.id}-${row.location.id}`} pagination={false} dataSource={editing.lines} columns={[{title:'SKU',render:(_,r)=>r.sku.code},{title:'库位',render:(_,r)=>r.location.code},{title:'审核前账面',dataIndex:'approvalBookTotal'},{title:'实盘',dataIndex:'countedTotal'},{title:'差异',dataIndex:'difference'},{title:'调整后可用',dataIndex:'availableAfter'},{title:'调整后占用',dataIndex:'reservedAfter'}]}/>} 
    </Modal>
  </Space>;
}
