package com.acme.training.wms.count;
import com.acme.training.wms.masterdata.MasterDataOption;
import java.time.Instant; import java.util.List;
public final class InventoryCountView implements java.io.Serializable {
    private final Long id; private final String countNo; private final InventoryCountStatus status; private final long version; private final MasterDataOption warehouse; private final List<InventoryCountLineView> lines; private final String createdBy; private final Instant createdAt; private final String note; private final String submittedBy; private final Instant submittedAt; private final String rejectedBy,rejectionReason,cancelledBy,cancellationReason,correctionOfCountNo,approvedBy,lastApprovalFailureCode; private final Instant rejectedAt,cancelledAt,approvedAt,lastApprovalFailureAt;
    public InventoryCountView(Long id,String no,InventoryCountStatus status,long version,MasterDataOption warehouse,List<InventoryCountLineView> lines,String by,Instant at,String note,String submittedBy,Instant submittedAt,String rejectedBy,Instant rejectedAt,String rejectionReason,String cancelledBy,Instant cancelledAt,String cancellationReason,String correctionOfCountNo,String approvedBy,Instant approvedAt,String lastApprovalFailureCode,Instant lastApprovalFailureAt){this.id=id;this.countNo=no;this.status=status;this.version=version;this.warehouse=warehouse;this.lines=lines;this.createdBy=by;this.createdAt=at;this.note=note;this.submittedBy=submittedBy;this.submittedAt=submittedAt;this.rejectedBy=rejectedBy;this.rejectedAt=rejectedAt;this.rejectionReason=rejectionReason;this.cancelledBy=cancelledBy;this.cancelledAt=cancelledAt;this.cancellationReason=cancellationReason;this.correctionOfCountNo=correctionOfCountNo;this.approvedBy=approvedBy;this.approvedAt=approvedAt;this.lastApprovalFailureCode=lastApprovalFailureCode;this.lastApprovalFailureAt=lastApprovalFailureAt;}
    public Long getId(){return id;} public String getCountNo(){return countNo;} public InventoryCountStatus getStatus(){return status;} public long getVersion(){return version;} public MasterDataOption getWarehouse(){return warehouse;} public List<InventoryCountLineView> getLines(){return lines;} public String getCreatedBy(){return createdBy;} public Instant getCreatedAt(){return createdAt;} public String getNote(){return note;} public String getSubmittedBy(){return submittedBy;} public Instant getSubmittedAt(){return submittedAt;}
    public String getRejectedBy(){return rejectedBy;} public Instant getRejectedAt(){return rejectedAt;} public String getRejectionReason(){return rejectionReason;} public String getCancelledBy(){return cancelledBy;} public Instant getCancelledAt(){return cancelledAt;} public String getCancellationReason(){return cancellationReason;}
    public String getCorrectionOfCountNo(){return correctionOfCountNo;}
    public String getApprovedBy(){return approvedBy;} public Instant getApprovedAt(){return approvedAt;}
    public String getLastApprovalFailureCode(){return lastApprovalFailureCode;} public Instant getLastApprovalFailureAt(){return lastApprovalFailureAt;}
}
