package com.acme.training;
import com.fasterxml.jackson.databind.*; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.test.web.servlet.*; import org.springframework.transaction.annotation.Transactional;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest @AutoConfigureMockMvc @Transactional
class T06CountRejectCancelIntegrationTest {
 @Autowired MockMvc mockMvc; @Autowired ObjectMapper json;
 @Test void submittedCountCanBeRejectedAndExplicitlyReopenedWithoutLosingRejectionHistory() throws Exception {JsonNode submitted=submitted("reject-flow");long id=submitted.path("id").asLong(),v=submitted.path("version").asLong();transition(id,v,"REJECT","reject-1","数量需复核","reviewer-b").andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("REJECTED")).andExpect(jsonPath("$.data.rejectedBy").value("reviewer-b")).andExpect(jsonPath("$.data.rejectionReason").value("数量需复核"));transition(id,v+1,"REOPEN","reopen-1",null,"counter-a").andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("DRAFT")).andExpect(jsonPath("$.data.rejectionReason").value("数量需复核"));}
 @Test void rejectionRequiresReasonAndKeepsSubmittedState() throws Exception {JsonNode submitted=submitted("reject-reason");long id=submitted.path("id").asLong(),v=submitted.path("version").asLong();transition(id,v,"REJECT","reject-no-reason","", "reviewer-b").andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value("INVALID_REQUEST"));mockMvc.perform(get("/api/wms/inventory-counts/{id}",id)).andExpect(jsonPath("$.data.status").value("SUBMITTED"));}
 @Test void draftCancellationReleasesScopeAndIsFinal() throws Exception {JsonNode draft=create("cancel-create");long id=draft.path("id").asLong(),v=draft.path("version").asLong();transition(id,v,"CANCEL","cancel-1","盘点计划取消","counter-a").andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("CANCELLED")).andExpect(jsonPath("$.data.cancelledBy").value("counter-a"));create("replacement-create");transition(id,v+1,"REOPEN","no-reopen",null,"counter-a").andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("WMS_COUNT_INVALID_STATE"));}
 @Test void transitionActionsHonorIdempotencyAndVersion() throws Exception {JsonNode submitted=submitted("transition-idem");long id=submitted.path("id").asLong(),v=submitted.path("version").asLong();transition(id,v,"REJECT","same-reject","复核","reviewer-b").andExpect(status().isOk());transition(id,v,"REJECT","same-reject","复核","reviewer-b").andExpect(status().isOk());transition(id,v,"REJECT","same-reject","其他原因","reviewer-b").andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("WMS_IDEMPOTENCY_CONFLICT"));transition(id,v,"REOPEN","stale-reopen",null,"counter-a").andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("WMS_COUNT_VERSION_CONFLICT"));}
 private JsonNode submitted(String prefix)throws Exception{JsonNode c=create(prefix+"-create");long id=c.path("id").asLong(),v=c.path("version").asLong();String saved=mockMvc.perform(put("/api/wms/inventory-counts/{id}",id).header("X-Operator","counter-a").contentType(MediaType.APPLICATION_JSON).content("{\"idempotencyKey\":\""+prefix+"-save\",\"expectedVersion\":"+v+",\"lines\":[{\"skuId\":303,\"locationId\":1,\"countedTotal\":10}]}" )).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();long sv=json.readTree(saved).path("data").path("version").asLong();String body=transition(id,sv,"SUBMIT",prefix+"-submit",null,"counter-a").andExpect(status().isOk()).andReturn().getResponse().getContentAsString();return json.readTree(body).path("data");}
 private JsonNode create(String key)throws Exception{String body=mockMvc.perform(post("/api/wms/inventory-counts").header("X-Operator","counter-a").contentType(MediaType.APPLICATION_JSON).content("{\"idempotencyKey\":\""+key+"\",\"warehouseId\":1,\"lines\":[{\"skuId\":303,\"locationId\":1}]}" )).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();return json.readTree(body).path("data");}
 private ResultActions transition(long id,long v,String action,String key,String reason,String operator)throws Exception{return mockMvc.perform(post("/api/wms/inventory-counts/{id}/transitions",id).header("X-Operator",operator).contentType(MediaType.APPLICATION_JSON).content("{\"action\":\""+action+"\",\"idempotencyKey\":\""+key+"\",\"expectedVersion\":"+v+(reason==null?"":",\"reason\":\""+reason+"\"")+"}"));}
}
